### PR TITLE
Feature/atr 17 master pxdb field attribute not matching property

### PR DESCRIPTION
**Pull request by SENya1990**

### CODE REVIEW

**Comment by SENya1990** [comment]
@k-s-popova please verify the following messages:
For PX1021 diagnostic - DAC property type doesn't correspond to the bound/unbound field attribute:
"The PXDBFieldAttribute type and property type do not correspond to each other"  - for the diagnostic
"Make the property type correspond to the attribute type."  - for the suggested code fix

For PX1023 diagnostic - multiple bound/unbound field attribute on DAC property:
"The DAC property can not be marked with multiple field attributes" - for diagnostic
"Remove other field attributes from the property." - for the code fix

**Comment by SENya1990** [comment]
@k-s-popova I'll change messages, thanks

**Comment by SENya1990** [comment]
@k-s-popova first message probably should not specify concrete attribute type:
"The type of DAC field attribute does not correspond to the property type"
Please verify

**Comment by k-s-popova** [comment]
@SENya1990, "The type of the DAC field attribute does not correspond to the property type"

**Comment by SENya1990** [comment]
@k-s-popova "Remove unnecessary field attributes from the property" message doesn't specify that the selected attribute will remain on the property. Shoul we specify it?

**Comment by k-s-popova** [comment]
@SENya1990, let's change as follows:
"Leave the selected field attribute and remove other field attributes from the property"

**Comment by SENya1990** [comment]
@k-s-popova Thanks!

**Pull request merged**
