### PR TITLE
Feature/atr 28 master px action non primary view

### PR DESCRIPTION
**Pull request by SENya1990**
Merge after ATR-143

### CODE REVIEW

**Comment by SENya1990** [comment]
@k-s-popova please verify messages for PX1012 diagnostic:
Diagnostic: "The action {0} is declared on non primary DAC and will not be visible in a toolbar. You should declare it on {1} DAC". The {0} stands is a placeholder for the action name and {1} is a placeholder for the primary DAC type.

CodeFix: "Change the action to be declared on primary DAC {0}".  The {0} is a placeholder for the  primary DAC type.

**Comment by SENya1990** [comment]
@k-s-popova thanks!

**Comment by dropsonic** [comment]
@SENya1990 there are some conflicts to resolve

**Comment by SENya1990** [comment]
@dropsonic resolved conflicts

**Pull request merged**
