### PR TITLE
Feature/atr 458 dev

### PR DESCRIPTION
**Pull request by SENya1990**

### CODE REVIEW

**Comment by SENya1990** [comment]
@k-s-popova  please review the name of suppress with a comment code fix when it is non nested (case of Acuminator installed as a nuget package):
`Suppress diagnostic {0} with Acuminator in a comment`
изображение

**Comment by SENya1990** [comment]
@k-s-popova should we change the title for a grouping code action too?
Suppress diagnostic {0} with Acuminator -> in a comment

**Comment by k-s-popova** [comment]
@SENya1990 , yes, I thought I suggested to change to "Suppress the {0} diagnostic with Acuminator", but I missed that it was not changed

**Comment by SENya1990** [comment]
Yes I forgot to change that. I'll make another PR in a minute

**Pull request merged**
